### ISSUE TITLE
Avg ping deviation

### ISSUE THREAD

**Issue by W4lter-Rabbit** [yuh25/Ping-Grapher#10]
Hello,

I would like to know if its possible to add average ping deviation, jitter or something similar. 
We have multiple acces points and they all produce annoying lag spikes. I'd like to know which one provides the most stable connection.

Also might i ask whats the difference between ping and latency within the plugin?

**Comment by yuh25** [comment]
I've quickly added jitter to the options on my end. Was this what you were thinking of?

> ![image](https://user-images.githubusercontent.com/11281828/168334694-5ae3d10f-b9ac-46a0-9018-8f4d0691b259.png)
> _Jitter while downloading a game_

> ![image](https://user-images.githubusercontent.com/11281828/168281185-03682f5a-36a4-4bb9-b7d3-e0ae4dbd869e.png)
> _~35ms spike_

and there is no difference in the ping and latency values, its just a different label I prefer.
