### ISSUE TITLE
Width/height adjustment

### ISSUE THREAD

**Issue by b-licorice** [yuh25/Ping-Grapher#11]
It'd be pretty nice to be able to customize the dimensions of the widget/graph!

**Comment by yuh25** [comment]
With the way the plugin is currently set up I don't think its possible to add the width/height settings back.

Currently you can change the dimensions by holding alt and dragging the edges of the plugin, right click will set it back to default.

**Comment by b-licorice** [comment]
Wow, I had absolutely no idea this was a feature to begin with! This will definitely work as an alternative, thanks!
