### ISSUE TITLE
Warnings when values reach beyond (personally tweakable) optimal values

### ISSUE THREAD

**Issue by Rowan-Mulder** [yuh25/Ping-Grapher#12]
I really like the customizability of the interface to make it small and blend in with the rest of the interfaces, so I can always have it on without it being too disturbing or in the way. This way, I also won't have to forget to turn the plugin back on when I need it the most, at the start of a raid.

![Customized interface](https://i.imgur.com/wDAjjVk.png)

Occasionally on my local network, someone takes high priority on quite a low bandwidth, affecting OSRS in such a way that the two Overclocked invocations in Tombs of Amascut for instance are near impossible. I only really start noticing high latency at Wardens and Ba-Ba, which I usually save til last. With me often forgetting to check the latency, finding it inconvenient to stabilize the network mid-raid, and having no ability to hop to a better world during a raid, a warning system would be very helpful.

Would it be possible to personally define maximum values (applies to selected labels ping/latency/tick) that would optionally trigger a notification and/or highlight the interface with a warning color? Perhaps a new 'Warning Color' could then overwrite the 'Overlay Background Color' until the values drop below warning levels again.

**Comment by yuh25** [comment]
Sorry for the delay but I've added your suggestion to the plugin and should be added once approved.

![image](https://user-images.githubusercontent.com/11281828/235350467-0de3ebc2-7b66-456b-8d56-598664491439.png)

![image](https://user-images.githubusercontent.com/11281828/235338095-ba0bd74d-6592-4749-a8c0-80c8b3c187a2.png)
