### ISSUE TITLE
displaying wrong ping

### ISSUE THREAD

**Issue by MrMkay97** [yuh25/Ping-Grapher#16]
since today the plugin constantly displays the wrong ping. Can anyone please fix that?

**Comment by yuh25** [comment]
Could you post a screenshot showing the issue and if possible any relevant runelite logs? I don't think noticed any issues with the plugin on my client. Thanks

**Comment by yuh25** [comment]
Closing this issue as I haven't heard back from you or had anyone else comment about having issues. 
Seems to be working fine.
![image](https://github.com/yuh25/Ping-Grapher/assets/11281828/c14e2628-d792-4f7c-b544-6a1a8ce33515)
