### ISSUE TITLE
Timed Out flashing

### ISSUE THREAD

**Issue by tyosrs** [yuh25/Ping-Grapher#17]
I have been using this plugin for a while but the past month, it happens on certain worlds but now its every world. It flashes for a second but ping doesnt change. ive tried multiple worlds. Different times of day. Reinstalled plugin, reinstalled rl.

**Comment by tyosrs** [comment]
![image](https://github.com/yuh25/Ping-Grapher/assets/147340329/2c22d4f2-1c03-4547-80a6-8e951ab7d6b0)

**Comment by tyosrs** [comment]
https://github.com/yuh25/Ping-Grapher/assets/147340329/192395c2-376c-41eb-bbb5-a0d2cf4f84a2

**Comment by Tiamtum** [comment]
Having the same issue. Coincidentally been having some nasty random disconnections the past week. Perhaps it's a Jagex problem. A cursory look at the code shows that when `pingGraphPlugin.getCurrentPing() < 0` the timed out message will appear (among other things) on the overlay. So why this condition is true in such a high frequency is the question.

**Comment by yuh25** [comment]
Hey, just checking if this is still occurring. It looks like the graph is graphing game ticks in the video which would be why it won't show "Timed out" pings.
