### ISSUE TITLE
Option to make outer border and background transparent

### ISSUE THREAD

**Issue by 0anth** [yuh25/Ping-Grapher#4]
Would it be possible to have the option to customize the appearance of the outer box separately to the graph box?

Current options affect both, example:

![1](https://user-images.githubusercontent.com/1083462/120790019-f9022180-c564-11eb-81e4-0e0e5cb54d0a.jpg)
![2](https://user-images.githubusercontent.com/1083462/120790026-fb647b80-c564-11eb-88d0-a6db6c72969b.jpg)

Example of customizing the two boxes seperately:

![3](https://user-images.githubusercontent.com/1083462/120790094-0fa87880-c565-11eb-90f7-6a1d681b3cf3.jpg)

**Comment by yuh25** [comment]
I've just updated the plugin so the settings will be separated once its up on the plugin hub.
