### ISSUE TITLE
The ability to hide the graph

### ISSUE THREAD

**Issue by JoshPaulie** [yuh25/Ping-Grapher#7]
A checkbox to turn the graph on and off would be nice. I'd rather just see my current and max ping.

**Comment by yuh25** [comment]
I've added it to my current version and it should be added to the plugin once I've cleaned it up and make sure other settings I'm working on don't break everything.

![image](https://user-images.githubusercontent.com/11281828/144748150-a8eb0b9a-bc2b-49e9-96cd-fb6fabe8b43f.png)

**Comment by JoshPaulie** [comment]
Awesome! Looking forward to it.

**Comment by JoshPaulie** [comment]
Looks great, thank you
