### ISSUE TITLE
Graph Game Ticks no longer works without Scale Between Max and Min ping

### ISSUE THREAD

**Issue by elkcarc** [yuh25/Ping-Grapher#8]
Previously the tick graph would be rendered normally and only show large spikes in the event of lag. Now the graph no longer renders without scaling between min/max ping.

Scaling between min/max with lagspike
![image](https://user-images.githubusercontent.com/42009371/146676670-ec0d3bf1-cce7-479f-b680-8f95602f2381.png)
Scaling without lagspike
![image](https://user-images.githubusercontent.com/42009371/146676689-46442a52-792d-42ff-b405-74de8d39e28f.png)
With graph game ticks and without scaling between min/max ping 
![image](https://user-images.githubusercontent.com/42009371/146676707-d3d1139e-68f1-47ca-8fa1-f37e6581a8c6.png)
Previous behavior before the most recent update without lagspike
![image](https://user-images.githubusercontent.com/42009371/146676738-00d2c942-43c7-42cc-b39c-239cfb6eef35.png)
Previous behavior before the most recent update with lagspike
![image](https://user-images.githubusercontent.com/42009371/146676753-8476db5d-63b7-4e6f-a90a-a3251e6bee0e.png)

**Comment by yuh25** [comment]
Thanks for letting me know. I think I've found the issue and it should be working again once it gets updated.
![image](https://user-images.githubusercontent.com/11281828/146678147-4eeba3cb-00e0-4c5b-8f52-b29219e31c59.png)
